version: "3"
networks:
  outside:
     external: true
services:
  server:
    build:
      context: ./
    volumes:
      - ./:/go/src/app
    ports:
      - 9292:9292

  api-test:
    build:
      context: ./
      dockerfile: Dockerfile-api-test
    links:
      - server
    networks:
      - outside
    environment:
      - ATTACHE_URL=http://localhost:8080
      - ATTACHE_SECRET_KEY=secretkey
      - TEST=test/attache/api/v1_test.rb
