version: "3"
services:
  server:
    build:
      context: ./
    volumes:
      - ./:/go/src/app
    ports:
      - 9292:9292

  api-test:
    build:
      context: ./
      dockerfile: Dockerfile-test
    links:
      - server
    environment:
      - ATTACHE_URL=http://server:9292
      - TEST=test/attache/api/v1_test.rb
